export type FlightInfoV1 = {
	td_id_decompression: string;
	td_id_weight_on_wheels: string;
	td_id_all_doors_closed: string;
	td_id_x2_pa_state: string;
	td_id_fltdata_ground_speed: string;
	td_id_fltdata_time_to_destination: string;
	td_id_fltdata_wind_speed: string;
	td_id_fltdata_mach: string;
	td_id_fltdata_boolean_heading: string;
	td_id_fltdata_gmt: string;
	td_id_fltdata_outside_air_temp: string;
	td_id_fltdata_head_wind_speed: string;
	td_id_fltdata_date: string;
	td_id_fltdata_distance_to_destination: string;
	td_id_fltdata_altitude: string;
	td_id_fltdata_present_position_latitude: string;
	td_id_fltdata_present_position_longitude: string;
	td_id_fltdata_destination_latitude: string;
	td_id_fltdata_destination_longitude: string;
	td_id_fltdata_destination_id: string;
	td_id_fltdata_departure_id: string;
	td_id_fltdata_flight_number: string;
	td_id_fltdata_destination_baggage_id: string;
	td_id_fltdata_departure_baggage_id: string;
	td_id_airframe_tail_number: 'D-';
	td_id_flight_phase: string;
	td_id_gmt_offset_departure: string;
	td_id_gmt_offset_destination: string;
	td_id_route_id: string;
	td_id_fltdata_time_at_origin: string;
	td_id_fltdata_time_at_destination: string;
	td_id_fltdata_distance_from_origin: string;
	td_id_fltdata_distance_traveled: string;
	td_id_fltdata_estimated_arrival_time: string;
	td_id_fltdata_time_at_takeoff: string;
	td_id_fltdata_departure_latitude: string;
	td_id_fltdata_departure_longitude: string;
	td_id_pdi_fltdata_departure_iata: string;
	td_id_pdi_fltdata_departure_time_scheduled: string;
	td_id_pdi_fltdata_arrival_iata: string;
	td_id_fltdata_wind_direction: string;
	td_id_media_date: string;
	td_id_extv_channel_listing_version: string;
	disclaimer: string;
};

export type FlightInfoV2 = {
	decompression_state: boolean;
	weight_on_wheels: boolean;
	all_doors_closed: number;
	ground_speed_knots: number;
	time_to_destination_minutes: number;
	wind_speed_knots?: number;
	flight_speed_mach?: number;
	boolean_heading_degree?: number;
	current_utc_time: string;
	outside_air_temp_celsius: null;
	head_wind_speed_knots: null;
	current_utc_date: string;
	distance_to_destination_nautical_miles: number;
	altitude_feet: number;
	destination_icao: string;
	departure_icao: string;
	flight_number: string;
	destination_iata: string;
	departure_iata: string;
	tail_number: string;
	flight_phase: string;
	departure_utc_offset_minutes: number;
	destination_utc_offset_minutes: number;
	route_id?: number;
	time_at_origin: string;
	time_at_destination: string;
	distance_from_departure_nautical_miles: number;
	distance_traveled_nautical_miles?: number;
	estimated_arrival_time_utc: string;
	takeoff_time_utc: string;
	wind_direction_degree?: number;
	media_date: string;
	extv_channel_listing_version: 1065;
	current_coordinates: { latitude: number; longitude: number };
	departure_coordinates: { latitude: number; longitude: number };
	destination_coordinates: { latitude: number; longitude: number };
	aircraft_type: string;
	all_doors_state: string | 'unknown';
	disclaimer: string;
	flight_id: string;
	flight_state: string;
	passenger_anouncement: string[];
	weight_on_wheels_state: string;
	distance_covered_percentage: number;
};

export type Status = {
	global_conn_enabled: boolean;
	internet_connectivity_status: boolean;
	time_until_coverage_change: number;
	total_coverage_remaining: number;
};

export type Weather = unknown[];

export type AirportInfo = {
	response_code: number;
	body: {
		icao: string;
		iata: string;
		airport: string;
		city: {
			en: string;
			fr: string;
			ja: string;
			de: string;
			'zh-cn': string;
			ar: string;
			'zh-tw': string;
			es: string;
			it: string;
			ko: string;
			pt: string;
			tr: string;
			th: string;
			nl: string;
			he: string;
			hi: string;
			ru: string;
			vi: string;
		};
		country: string;
		timediv: string;
		state: string;
		type: string;
		gmtvar: string;
		dstvar1: string;
		dststtm1: string;
		dststdt1: string;
		dststst1: string;
		dstedtm1: string;
		dsteddt1: string;
		dstedst1: string;
		dataind: string;
		dstvar2: string;
		dststtm2: string;
		dststdt2: string;
		dststst2: string;
		dstedtm2: string;
		dsteddt2: string;
		dstdsst2: string;
		latt: string;
		long: string;
	};
}[];
